version: '3.8'

services:
  app:
    build: .
    container_name: sign_translate_app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4200:4200"
    environment:
      NODE_ENV: development
